services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: tamir
      POSTGRES_PASSWORD: 14032712
      POSTGRES_DB: lms_project
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      HOST: postgres
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/static

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      HOST: postgres
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      HOST: postgres
    env_file:
      - .env
    depends_on:
      - redis
      - postgres


volumes:
  static_volume:
  pg_data:
