# Generated by Django 5.2 on 2025-04-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название курса', max_length=255, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='materials/preview', verbose_name='Превью курса')),
                ('description', models.TextField(blank=True, help_text='Укажите описание курса', null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название урока', max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Укажите описание урока', null=True, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='materials/preview', verbose_name='Превью курса')),
                ('link_to_video', models.CharField(blank=True, help_text='Укажите ссылку на видео', max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='materials.course')),
            ],
        ),
    ]
